import { ThemeProvider } from '@/components/context/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';
import localFont from 'next/font/local';
import Script from 'next/script';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata = {
	title: 'Investment Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			{/* Load the AnyChart libraries using next/script */}
			<Script
				src='https://cdn.anychart.com/releases/8.11.1/js/anychart-core.min.js'
				strategy='beforeInteractive'
			/>
			<Script
				src='https://cdn.anychart.com/releases/8.11.1/js/anychart-stock.min.js'
				strategy='beforeInteractive'
			/>
			<Script
				src='https://cdn.anychart.com/releases/8.11.1/js/anychart-data-adapter.min.js'
				strategy='beforeInteractive'
			/>

			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
					{children}
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
